// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv dotenv-expand
import { expand } from 'dotenv-expand';
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

// Expande as variáveis ${} contidas no process.env
expand({ parsed: process.env as any });

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Agora o process.env['DATABASE_URL'] já estará com as variáveis resolvidas
    url: process.env['DATABASE_URL'],
  },
});
